title: Pavan Ravindra
email: pravin4094@gmail.com
description: Undergraduate at the University of Maryland
baseurl: "/pavanravindra.github.io"
url: "localhost:4000"
github_username:  pavanravindra

# Build settings
remote_theme: beautiful-jekyll-theme
#theme: beautiful-jekyll-theme
plugins:
  - jekyll-feed


# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
